<a href="https://colab.research.google.com/github/malavikasreekumar/Bank-_Exit/blob/master/Bank_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [3]:
cd gdrive

/content/gdrive


In [5]:
cd My Drive

[Errno 2] No such file or directory: 'My Drive'
/content/gdrive/My Drive


In [6]:
ls

 3a-knn.gslides                       '9B-kmeans-clustering (2).gslides'
 3b-features.gslides                  '9B-kmeans-clustering (3).gslides'
 3c-feature-extraction.gslides         9B-kmeans-clustering.gslides
'3d-collab-filtering (1).gslides'     '9C-AHC-MOG (1).gslides'
 3d-collab-filtering.gslides           9C-AHC-MOG.gslides
 4a-probability-basics.gslides         Assessment.gform
 4b-Bayesian-learning.gslides          Churn_Modelling.csv
'4c-Naive-Bayes (1).gslides'          'Colab Notebooks'/
 4c-Naive-Bayes.gslides               'Customer Feedback (1).gform'
'5a-logistic-regression (1).gslides'  'Customer Feedback.gform'
'5a-logistic-regression (2).gslides'   dataset/
 5a-logistic-regression.gslides       'Delta Solution  Assessment Form.gform'
 5b-SVM.gslides                       'DL '/
'7A-CLT1 (1).gslides'                  Dog_Cat/
 7A-CLT1.gslides                      'Getting started.pdf'
 7B-CLT2-Infinite.gslides             'K-Nearest Neighbours.gslides'
 8A-ensemble1

In [0]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
#Importing Dataset
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13]

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])

labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [12]:
"""onehotencoder=OneHotEncoder([1])
X=onehotencoder.fit_transform(X).toarray()
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)"""

from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
 
X = np.array(columnTransformer.fit_transform(X), dtype = np.str)
 
X = X[:, 1:]
print(X)

[['0.0' '0.0' '619' ... '1' '1' '101348.88']
 ['0.0' '1.0' '608' ... '0' '1' '112542.58']
 ['0.0' '0.0' '502' ... '1' '0' '113931.57']
 ...
 ['0.0' '0.0' '709' ... '0' '1' '42085.58']
 ['1.0' '0.0' '772' ... '1' '0' '92888.52']
 ['0.0' '0.0' '792' ... '1' '0' '38190.78']]


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
#Importing keras
import keras

Using TensorFlow backend.


In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
#Initialising ANN
classifier=Sequential()

In [0]:
#Adding input layer and first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform', activation='relu',input_dim=11))

In [0]:
classifier.add(Dense(units=6,kernel_initializer='uniform', activation='relu'))

In [0]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [0]:
#Compiling ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 3s 380us/step - loss: 0.4188 - accuracy: 0.8196
Epoch 2/100
8000/8000 [==============================] - 3s 365us/step - loss: 0.4160 - accuracy: 0.8249
Epoch 3/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.4142 - accuracy: 0.8300
Epoch 4/100
8000/8000 [==============================] - 3s 399us/step - loss: 0.4132 - accuracy: 0.8306
Epoch 5/100
8000/8000 [==============================] - 3s 371us/step - loss: 0.4121 - accuracy: 0.8316
Epoch 6/100
8000/8000 [==============================] - 3s 368us/step - loss: 0.4112 - accuracy: 0.8303
Epoch 7/100
8000/8000 [==============================] - 3s 382us/step - loss: 0.4104 - accuracy: 0.8340
Epoch 8/100
8000/8000 [==============================] - 3s 371us/step - loss: 0.4096 - accuracy: 0.8315
Epoch 9/100
8000/8000 [==============================] - 3s 358us/step - loss: 0.4088 - accuracy: 0.8335
Epoch 10/100
8000/8000 [==============================]

In [29]:
y_pred=classifier.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.5)

[[0.248668  ]
 [0.3332343 ]
 [0.19707057]
 ...
 [0.17409724]
 [0.16817231]
 [0.12607872]]


In [31]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1546   49]
 [ 265  140]]
